import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { Annotation } from './annotations';

/**
 * Build a temporary bridge.ck that declares the same globals as annotated
 * user code and maps OSC /chuck/<name> → those globals.
 */
export function writeBridgeFile(
  annotations: Annotation[],
  oscPort: number
): { path: string; source: string } {
  const source = generateBridgeSource(annotations, oscPort);
  const outPath = path.join(os.tmpdir(), 'chuck-live-bridge.ck');
  fs.writeFileSync(outPath, source, 'utf8');
  return { path: outPath, source };
}

export function generateBridgeSource(
  annotations: Annotation[],
  oscPort: number
): string {
  const lines: string[] = [
    '// Auto-generated by ChucK Live — do not edit by hand',
    `// OSC listen port ${oscPort}`,
    '',
  ];

  for (const a of annotations) {
    if (a.kind === 'knob') {
      lines.push(`global ${a.type} ${a.name};`);
    } else {
      lines.push(`global Event ${a.name};`);
    }
  }

  lines.push(
    '',
    'OscIn oin;',
    `${oscPort} => oin.port;`,
    ''
  );

  for (const a of annotations) {
    if (a.kind === 'knob') {
      // int knobs still arrive as float from the webview; accept ,f
      lines.push(`oin.addAddress("/chuck/${a.name},f");`);
    } else {
      lines.push(`oin.addAddress("/chuck/${a.name},i");`);
    }
  }

  lines.push(
    '',
    'OscMsg msg;',
    'while (true) {',
    '  oin => now;',
    '  while (oin.recv(msg)) {'
  );

  for (const a of annotations) {
    if (a.kind === 'knob') {
      if (a.type === 'int') {
        lines.push(
          `    if (msg.address == "/chuck/${a.name}") Std.ftoi(msg.getFloat(0)) => ${a.name};`
        );
      } else {
        lines.push(
          `    if (msg.address == "/chuck/${a.name}") msg.getFloat(0) => ${a.name};`
        );
      }
    } else {
      lines.push(
        `    if (msg.address == "/chuck/${a.name}") ${a.name}.broadcast();`
      );
    }
  }

  lines.push('  }', '}', '');
  return lines.join('\n');
}

/** Merge by name; later list wins. */
export function mergeAnnotationLists(
  ...lists: Annotation[][]
): Annotation[] {
  const map = new Map<string, Annotation>();
  for (const list of lists) {
    for (const a of list) {
      map.set(a.name, a);
    }
  }
  return [...map.values()];
}
