import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { Annotation, ModTarget } from './annotations';
import { modBridgeRouteGlobals } from './modGen';

/** Shared sequencer / transport bus — reserved `live_*` prefix. */
export const LIVE_TRANSPORT = {
  bpm: 'live_bpm',
  step: 'live_step',
  stepDur: 'live_stepDur',
  tick: 'live_tick',
  running: 'live_running',
  /** Host → ChucK: 1 = run, 0 = stop (transport shred). */
  cmd: 'live_cmd',
  /** Host → ChucK: 1 = swing on, 0 = off. */
  swing: 'live_swing',
} as const;

const LIVE_NAMES = new Set<string>(Object.values(LIVE_TRANSPORT));

/**
 * Build a temporary bridge.ck that declares the same globals as annotated
 * user code and maps OSC /chuck/<name> → those globals.
 * Always includes the live_* transport bus.
 */
export function writeBridgeFile(
  annotations: Annotation[],
  oscPort: number,
  modTargets: ModTarget[] = []
): { path: string; source: string } {
  const source = generateBridgeSource(annotations, oscPort, modTargets);
  const outPath = path.join(os.tmpdir(), 'chuck-live-bridge.ck');
  fs.writeFileSync(outPath, source, 'utf8');
  return { path: outPath, source };
}

export function generateBridgeSource(
  annotations: Annotation[],
  oscPort: number,
  modTargets: ModTarget[] = []
): string {
  const lines: string[] = [
    '// Auto-generated by ChucK Live — do not edit by hand',
    `// OSC listen port ${oscPort}`,
    '// Transport bus: live_bpm, live_step, live_stepDur, live_tick, live_running',
    '',
    `global float ${LIVE_TRANSPORT.bpm};`,
    `global int ${LIVE_TRANSPORT.step};`,
    `global float ${LIVE_TRANSPORT.stepDur};`,
    `global Event ${LIVE_TRANSPORT.tick};`,
    `global int ${LIVE_TRANSPORT.running};`,
    `global int ${LIVE_TRANSPORT.cmd};`,
    `global int ${LIVE_TRANSPORT.swing};`,
    '',
    '// Transport bus owned by transport shred + host OSC — do not assign here.',
    '// (bridge OTF-replace must not reset live_step, live_running, or BPM).',
    '',
  ];

  for (const a of annotations) {
    if (LIVE_NAMES.has(a.name)) {
      continue;
    }
    if (a.kind === 'knob') {
      lines.push(`global ${a.type} ${a.name};`);
    } else {
      lines.push(`global Event ${a.name};`);
    }
  }

  const routeGlobals = modBridgeRouteGlobals(modTargets);
  for (const r of routeGlobals) {
    lines.push(`global int ${r.srcName};`);
    lines.push(`global float ${r.depthName};`);
  }

  lines.push(
    '',
    'OscIn oin;',
    `${oscPort} => oin.port;`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.bpm},f");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.step},f");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.stepDur},f");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.tick},i");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.running},f");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.cmd},i");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.swing},i");`,
    ''
  );

  for (const a of annotations) {
    if (LIVE_NAMES.has(a.name)) {
      continue;
    }
    if (a.kind === 'knob') {
      lines.push(`oin.addAddress("/chuck/${a.name},f");`);
    } else {
      lines.push(`oin.addAddress("/chuck/${a.name},i");`);
    }
  }

  for (const r of routeGlobals) {
    lines.push(`oin.addAddress("/chuck/${r.srcName},i");`);
    lines.push(`oin.addAddress("/chuck/${r.depthName},f");`);
  }

  lines.push(
    '',
    'OscMsg msg;',
    'while (true) {',
    '  oin => now;',
    '  while (oin.recv(msg)) {'
  );

  lines.push(
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.bpm}") {`,
    `      msg.getFloat(0) => ${LIVE_TRANSPORT.bpm};`,
    `      (60.0 / Math.max(40.0, ${LIVE_TRANSPORT.bpm}) / 4.0) => ${LIVE_TRANSPORT.stepDur};`,
    '    }',
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.step}") Std.ftoi(msg.getFloat(0)) => ${LIVE_TRANSPORT.step};`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.stepDur}") msg.getFloat(0) => ${LIVE_TRANSPORT.stepDur};`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.tick}") ${LIVE_TRANSPORT.tick}.broadcast();`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.running}") Std.ftoi(msg.getFloat(0)) => ${LIVE_TRANSPORT.running};`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.cmd}") Std.ftoi(msg.getInt(0)) => ${LIVE_TRANSPORT.cmd};`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.swing}") Std.ftoi(msg.getInt(0)) => ${LIVE_TRANSPORT.swing};`
  );

  for (const a of annotations) {
    if (LIVE_NAMES.has(a.name)) {
      continue;
    }
    if (a.kind === 'knob') {
      if (a.type === 'int') {
        lines.push(
          `    if (msg.address == "/chuck/${a.name}") Std.ftoi(msg.getFloat(0)) => ${a.name};`
        );
      } else {
        lines.push(
          `    if (msg.address == "/chuck/${a.name}") msg.getFloat(0) => ${a.name};`
        );
      }
    } else {
      lines.push(
        `    if (msg.address == "/chuck/${a.name}") ${a.name}.broadcast();`
      );
    }
  }

  for (const r of routeGlobals) {
    lines.push(
      `    if (msg.address == "/chuck/${r.srcName}") Std.ftoi(msg.getInt(0)) => ${r.srcName};`
    );
    lines.push(
      `    if (msg.address == "/chuck/${r.depthName}") msg.getFloat(0) => ${r.depthName};`
    );
  }

  lines.push('  }', '}', '');
  return lines.join('\n');
}

/** Merge by name; later list wins. */
export function mergeAnnotationLists(
  ...lists: Annotation[][]
): Annotation[] {
  const map = new Map<string, Annotation>();
  for (const list of lists) {
    for (const a of list) {
      map.set(a.name, a);
    }
  }
  return [...map.values()];
}
