import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { Annotation, ModTarget } from './annotations';
import { modBridgeRouteGlobals } from './modGen';

/** Shared sequencer / transport bus — reserved `live_*` prefix. */
export const LIVE_TRANSPORT = {
  bpm: 'live_bpm',
  step: 'live_step',
  stepDur: 'live_stepDur',
  tick: 'live_tick',
  running: 'live_running',
  /** Host → ChucK: 1 = run, 0 = stop (transport shred). */
  cmd: 'live_cmd',
  /** Host → ChucK: 1 = swing on, 0 = off. */
  swing: 'live_swing',
} as const;

/**
 * Pattern / mix patch bus — written by OSC, read by transport.
 * Pending arrays are host-writable; live arrays swap on commit / bar wrap.
 */
export const LIVE_SEQ = {
  g: 'live_seq_g',
  v: 'live_seq_v',
  p: 'live_seq_p',
  gPend: 'live_seq_g_pend',
  vPend: 'live_seq_v_pend',
  pPend: 'live_seq_p_pend',
  muted: 'live_seq_muted',
  solo: 'live_seq_solo',
  run: 'live_seq_run',
  swingAmt: 'live_seq_swing',
  mutedPend: 'live_seq_muted_pend',
  soloPend: 'live_seq_solo_pend',
  runPend: 'live_seq_run_pend',
  swingPend: 'live_seq_swing_pend',
  armed: 'live_seq_armed',
  commit: 'live_seq_commit',
} as const;

const LIVE_NAMES = new Set<string>([
  ...Object.values(LIVE_TRANSPORT),
  ...Object.values(LIVE_SEQ),
]);

/**
 * Build a temporary bridge.ck that declares the same globals as annotated
 * user code and maps OSC /chuck/<name> → those globals.
 * Always includes the live_* transport + seq patch bus.
 */
export function writeBridgeFile(
  annotations: Annotation[],
  oscPort: number,
  modTargets: ModTarget[] = []
): { path: string; source: string } {
  const source = generateBridgeSource(annotations, oscPort, modTargets);
  const outPath = path.join(os.tmpdir(), 'chuck-live-bridge.ck');
  fs.writeFileSync(outPath, source, 'utf8');
  return { path: outPath, source };
}

export function generateBridgeSource(
  annotations: Annotation[],
  oscPort: number,
  modTargets: ModTarget[] = []
): string {
  const lines: string[] = [
    '// Auto-generated by ChucK Live — do not edit by hand',
    `// OSC listen port ${oscPort}`,
    '// Transport bus + live_seq_* pattern patch (no default assigns)',
    '',
    `global float ${LIVE_TRANSPORT.bpm};`,
    `global int ${LIVE_TRANSPORT.step};`,
    `global float ${LIVE_TRANSPORT.stepDur};`,
    `global Event ${LIVE_TRANSPORT.tick};`,
    `global int ${LIVE_TRANSPORT.running};`,
    `global int ${LIVE_TRANSPORT.cmd};`,
    `global int ${LIVE_TRANSPORT.swing};`,
    '',
    `global int ${LIVE_SEQ.g}[256];`,
    `global float ${LIVE_SEQ.v}[256];`,
    `global float ${LIVE_SEQ.p}[256];`,
    `global int ${LIVE_SEQ.gPend}[256];`,
    `global float ${LIVE_SEQ.vPend}[256];`,
    `global float ${LIVE_SEQ.pPend}[256];`,
    `global int ${LIVE_SEQ.muted}[16];`,
    `global int ${LIVE_SEQ.solo}[16];`,
    `global int ${LIVE_SEQ.run}[16];`,
    `global float ${LIVE_SEQ.swingAmt}[16];`,
    `global int ${LIVE_SEQ.mutedPend}[16];`,
    `global int ${LIVE_SEQ.soloPend}[16];`,
    `global int ${LIVE_SEQ.runPend}[16];`,
    `global float ${LIVE_SEQ.swingPend}[16];`,
    `global int ${LIVE_SEQ.armed};`,
    `global int ${LIVE_SEQ.commit};`,
    '',
    '// Transport bus owned by transport shred + host OSC — do not assign here.',
    '// (bridge OTF-replace must not reset live_step, live_running, or BPM).',
    '',
  ];

  for (const a of annotations) {
    if (LIVE_NAMES.has(a.name)) {
      continue;
    }
    if (a.kind === 'knob') {
      lines.push(`global ${a.type} ${a.name};`);
    } else {
      lines.push(`global Event ${a.name};`);
    }
  }

  const routeGlobals = modBridgeRouteGlobals(modTargets);
  for (const r of routeGlobals) {
    lines.push(`global int ${r.srcName};`);
    lines.push(`global float ${r.depthName};`);
  }

  lines.push(
    '',
    'OscIn oin;',
    `${oscPort} => oin.port;`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.bpm},f");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.step},f");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.stepDur},f");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.tick},i");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.running},f");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.cmd},i");`,
    `oin.addAddress("/chuck/${LIVE_TRANSPORT.swing},i");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.g},iii");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.v},iif");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.p},iif");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.muted},ii");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.solo},ii");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.run},ii");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.swingAmt},if");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.armed},i");`,
    `oin.addAddress("/chuck/${LIVE_SEQ.commit},i");`,
    ''
  );

  for (const a of annotations) {
    if (LIVE_NAMES.has(a.name)) {
      continue;
    }
    if (a.kind === 'knob') {
      lines.push(`oin.addAddress("/chuck/${a.name},f");`);
    } else {
      lines.push(`oin.addAddress("/chuck/${a.name},i");`);
    }
  }

  for (const r of routeGlobals) {
    lines.push(`oin.addAddress("/chuck/${r.srcName},i");`);
    lines.push(`oin.addAddress("/chuck/${r.depthName},f");`);
  }

  lines.push(
    '',
    'OscMsg msg;',
    'while (true) {',
    '  oin => now;',
    '  while (oin.recv(msg)) {'
  );

  lines.push(
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.bpm}") {`,
    `      msg.getFloat(0) => ${LIVE_TRANSPORT.bpm};`,
    `      (60.0 / Math.max(40.0, ${LIVE_TRANSPORT.bpm}) / 4.0) => ${LIVE_TRANSPORT.stepDur};`,
    '    }',
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.step}") Std.ftoi(msg.getFloat(0)) => ${LIVE_TRANSPORT.step};`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.stepDur}") msg.getFloat(0) => ${LIVE_TRANSPORT.stepDur};`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.tick}") ${LIVE_TRANSPORT.tick}.broadcast();`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.running}") Std.ftoi(msg.getFloat(0)) => ${LIVE_TRANSPORT.running};`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.cmd}") Std.ftoi(msg.getInt(0)) => ${LIVE_TRANSPORT.cmd};`,
    `    if (msg.address == "/chuck/${LIVE_TRANSPORT.swing}") Std.ftoi(msg.getInt(0)) => ${LIVE_TRANSPORT.swing};`,
    `    if (msg.address == "/chuck/${LIVE_SEQ.g}") {`,
    '      msg.getInt(0) => int tr;',
    '      msg.getInt(1) => int st;',
    '      if (tr >= 0 && tr < 16 && st >= 0 && st < 16) {',
    '        tr * 16 + st => int idx;',
    `        msg.getInt(2) => ${LIVE_SEQ.gPend}[idx];`,
    '      }',
    '    }',
    `    if (msg.address == "/chuck/${LIVE_SEQ.v}") {`,
    '      msg.getInt(0) => int tr;',
    '      msg.getInt(1) => int st;',
    '      if (tr >= 0 && tr < 16 && st >= 0 && st < 16) {',
    '        tr * 16 + st => int idx;',
    `        msg.getFloat(2) => ${LIVE_SEQ.vPend}[idx];`,
    '      }',
    '    }',
    `    if (msg.address == "/chuck/${LIVE_SEQ.p}") {`,
    '      msg.getInt(0) => int tr;',
    '      msg.getInt(1) => int st;',
    '      if (tr >= 0 && tr < 16 && st >= 0 && st < 16) {',
    '        tr * 16 + st => int idx;',
    `        msg.getFloat(2) => ${LIVE_SEQ.pPend}[idx];`,
    '      }',
    '    }',
    `    if (msg.address == "/chuck/${LIVE_SEQ.muted}") {`,
    '      msg.getInt(0) => int tr;',
    `      if (tr >= 0 && tr < 16) msg.getInt(1) => ${LIVE_SEQ.mutedPend}[tr];`,
    '    }',
    `    if (msg.address == "/chuck/${LIVE_SEQ.solo}") {`,
    '      msg.getInt(0) => int tr;',
    `      if (tr >= 0 && tr < 16) msg.getInt(1) => ${LIVE_SEQ.soloPend}[tr];`,
    '    }',
    `    if (msg.address == "/chuck/${LIVE_SEQ.run}") {`,
    '      msg.getInt(0) => int tr;',
    `      if (tr >= 0 && tr < 16) msg.getInt(1) => ${LIVE_SEQ.runPend}[tr];`,
    '    }',
    `    if (msg.address == "/chuck/${LIVE_SEQ.swingAmt}") {`,
    '      msg.getInt(0) => int tr;',
    `      if (tr >= 0 && tr < 16) msg.getFloat(1) => ${LIVE_SEQ.swingPend}[tr];`,
    '    }',
    `    if (msg.address == "/chuck/${LIVE_SEQ.armed}") msg.getInt(0) => ${LIVE_SEQ.armed};`,
    `    if (msg.address == "/chuck/${LIVE_SEQ.commit}") msg.getInt(0) => ${LIVE_SEQ.commit};`
  );

  for (const a of annotations) {
    if (LIVE_NAMES.has(a.name)) {
      continue;
    }
    if (a.kind === 'knob') {
      if (a.type === 'int') {
        lines.push(
          `    if (msg.address == "/chuck/${a.name}") Std.ftoi(msg.getFloat(0)) => ${a.name};`
        );
      } else {
        lines.push(
          `    if (msg.address == "/chuck/${a.name}") msg.getFloat(0) => ${a.name};`
        );
      }
    } else {
      lines.push(
        `    if (msg.address == "/chuck/${a.name}") ${a.name}.broadcast();`
      );
    }
  }

  for (const r of routeGlobals) {
    lines.push(
      `    if (msg.address == "/chuck/${r.srcName}") Std.ftoi(msg.getInt(0)) => ${r.srcName};`
    );
    lines.push(
      `    if (msg.address == "/chuck/${r.depthName}") msg.getFloat(0) => ${r.depthName};`
    );
  }

  lines.push('  }', '}', '');
  return lines.join('\n');
}

/** Merge by name; later list wins. */
export function mergeAnnotationLists(
  ...lists: Annotation[][]
): Annotation[] {
  const map = new Map<string, Annotation>();
  for (const list of lists) {
    for (const a of list) {
      map.set(a.name, a);
    }
  }
  return [...map.values()];
}
