import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

/**
 * Build a temporary meter.ck that tracks dac L/R peaks and sends OSC
 * /chuck/vu (two floats) to the extension.
 */
export function writeMeterFile(
  meterPort: number,
  host = '127.0.0.1'
): { path: string; source: string } {
  const source = generateMeterSource(meterPort, host);
  const outPath = path.join(os.tmpdir(), 'chuck-live-meter.ck');
  fs.writeFileSync(outPath, source, 'utf8');
  return { path: outPath, source };
}

export function generateMeterSource(
  meterPort: number,
  host = '127.0.0.1'
): string {
  return `// Auto-generated by ChucK Live — do not edit by hand
// Peak VU: dac L/R → OSC /chuck/vu @ ${host}:${meterPort}

0.0 => float peakL;
0.0 => float peakR;
// Per-sample release (~50 ms at 44.1 kHz)
Math.pow(0.001, 1.0 / (0.05 * 44100.0)) => float decay;

fun void trackL() {
  while (true) {
    Math.fabs(dac.chan(0).last()) => float s;
    if (s > peakL) {
      s => peakL;
    } else {
      peakL * decay => peakL;
    }
    1::samp => now;
  }
}

fun void trackR() {
  while (true) {
    Math.fabs(dac.chan(1).last()) => float s;
    if (s > peakR) {
      s => peakR;
    } else {
      peakR * decay => peakR;
    }
    1::samp => now;
  }
}

spork ~ trackL();
spork ~ trackR();

OscOut xmit;
xmit.dest("${host}", ${meterPort});

while (true) {
  xmit.start("/chuck/vu");
  xmit.add(peakL);
  xmit.add(peakR);
  xmit.send();
  25::ms => now;
}
`;
}
