import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

/** One module peak tap: global Gain name + shred id for OSC ordering. */
export interface MeterTap {
  /** ChucK `global Gain` identifier (e.g. sine_meter). */
  name: string;
  /** Shred id — host maps extra /chuck/vu floats → this id. */
  shredId: number;
}

/**
 * Basename → legal ChucK id + `_meter` (sine.ck → sine_meter, bus-fx.ck → bus_fx_meter).
 */
export function meterTapName(fileOrTitle: string): string {
  const base = path.basename(fileOrTitle).replace(/\.ck$/i, '');
  let id = base.replace(/[^a-zA-Z0-9_]/g, '_');
  if (!/^[a-zA-Z_]/.test(id)) {
    id = `_${id}`;
  }
  return `${id}_meter`;
}

/** Global float written by the module peak spork (`sine_meter` → `sine_meter_p`). */
export function meterPeakFloat(tapName: string): string {
  return `${tapName}_p`;
}

/**
 * Build a temporary meter.ck that tracks dac L/R + per-module peak floats
 * and sends OSC /chuck/vu (l, r, then one float per tap).
 */
export function writeMeterFile(
  meterPort: number,
  taps: MeterTap[] = [],
  host = '127.0.0.1'
): { path: string; source: string } {
  const source = generateMeterSource(meterPort, taps, host);
  const outPath = path.join(os.tmpdir(), 'chuck-live-meter.ck');
  fs.writeFileSync(outPath, source, 'utf8');
  return { path: outPath, source };
}

export function generateMeterSource(
  meterPort: number,
  taps: MeterTap[] = [],
  host = '127.0.0.1'
): string {
  const unique = dedupeTaps(taps);
  const peakNames = unique.map((t) => meterPeakFloat(t.name));
  const globals = peakNames.map((n) => `global float ${n};`).join('\n');
  const addPeaks = peakNames
    .map((n) => `  xmit.add(${n});`)
    .join('\n');

  const tapComment =
    unique.length === 0
      ? '// No module peak floats yet'
      : `// Extra /chuck/vu floats after L/R:\n${unique
          .map(
            (t, i) =>
              `//   [${i + 2}] shred #${t.shredId} → ${meterPeakFloat(t.name)}`
          )
          .join('\n')}`;

  return `// Auto-generated by ChucK Live — do not edit by hand
// dac L/R + module peaks → OSC /chuck/vu @ ${host}:${meterPort}
${tapComment}

${globals}

0.0 => float peakL;
0.0 => float peakR;
// ~50 ms release at 40 Hz UI rate (25::ms steps) — do not track per-sample.
Math.pow(0.001, 1.0 / (0.05 * 40.0)) => float decay;

OscOut xmit;
xmit.dest("${host}", ${meterPort});

// Single shred loop — sporked peak trackers survive OTF replace and burn CPU.
while (true) {
  Math.fabs(dac.chan(0).last()) => float sL;
  if (sL > peakL) {
    sL => peakL;
  } else {
    peakL * decay => peakL;
  }
  Math.fabs(dac.chan(1).last()) => float sR;
  if (sR > peakR) {
    sR => peakR;
  } else {
    peakR * decay => peakR;
  }
  xmit.start("/chuck/vu");
  xmit.add(peakL);
  xmit.add(peakR);
${addPeaks}
  xmit.send();
  25::ms => now;
}
`;
}

function dedupeTaps(taps: MeterTap[]): MeterTap[] {
  const seen = new Set<string>();
  const out: MeterTap[] = [];
  for (const t of taps) {
    if (!t.name || seen.has(t.name)) {
      continue;
    }
    seen.add(t.name);
    out.push(t);
  }
  return out;
}
