import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { ModSource, ModTarget } from './annotations';

export interface ModCodegenInput {
  sources: ModSource[];
  targets: ModTarget[];
  /** dst modName → active route */
  routes: Map<string, { srcIndex: number; depth: number }>;
}

export function writeModMatrixFile(input: ModCodegenInput): {
  path: string;
  source: string;
} {
  const source = generateModMatrixSource(input);
  const outPath = path.join(os.tmpdir(), 'chuck-live-mod-matrix.ck');
  fs.writeFileSync(outPath, source, 'utf8');
  return { path: outPath, source };
}

export function generateModMatrixSource(input: ModCodegenInput): string {
  const { sources, targets, routes } = input;
  const lines: string[] = [
    '// Auto-generated by ChucK Live — do not edit by hand',
    '// Mod matrix: applies source → destination routes at control rate',
    '',
  ];

  const declared = new Set<string>();

  const declFloat = (name: string): void => {
    if (declared.has(name)) {
      return;
    }
    declared.add(name);
    lines.push(`global float ${name};`);
  };
  const declInt = (name: string): void => {
    if (declared.has(name)) {
      return;
    }
    declared.add(name);
    lines.push(`global int ${name};`);
  };

  for (const s of sources) {
    declFloat(s.name);
  }
  for (const t of targets) {
    declFloat(t.modName);
    declInt(t.srcName);
    declFloat(t.depthName);
  }

  lines.push('');

  for (const t of targets) {
    const route = routes.get(t.modName);
    const srcIdx = route?.srcIndex ?? 0;
    const depth = route?.depth ?? 0;
    lines.push(`0 => ${t.srcName};`);
    lines.push(`0.0 => ${t.depthName};`);
    if (srcIdx > 0) {
      lines.push(`${srcIdx} => ${t.srcName};`);
      lines.push(`${depth} => ${t.depthName};`);
    }
  }

  lines.push('', 'spork ~ applyRoutes();', 'while (true) 20::ms => now;', '');

  lines.push('fun void applyRoutes() {');
  lines.push('  while (true) {');

  for (const t of targets) {
    lines.push(`    0.0 => ${t.modName};`);
    if (sources.length === 0) {
      continue;
    }
    for (const s of sources) {
      if (!s.index) {
        continue;
      }
      lines.push(
        `    if (${t.srcName} == ${s.index}) ${s.name} * ${t.depthName} => ${t.modName};`
      );
    }
  }

  lines.push('    1::ms => now;');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/** Route globals the OSC bridge must declare. */
export function modBridgeRouteGlobals(
  targets: ModTarget[]
): { srcName: string; depthName: string }[] {
  const out: { srcName: string; depthName: string }[] = [];
  const seen = new Set<string>();
  for (const t of targets) {
    const key = `${t.srcName}|${t.depthName}`;
    if (!seen.has(key)) {
      seen.add(key);
      out.push({ srcName: t.srcName, depthName: t.depthName });
    }
  }
  return out;
}
