import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { LIVE_TRANSPORT, LIVE_SEQ } from './bridgeGen';

/** One sequencer track baked into the transport shred. */
export interface TransportTrack {
  name: string;
  kind: 'float' | 'gate';
  /** Optional Event name for float lanes (gate bang). */
  gate?: string;
  muted: boolean;
  solo: boolean;
  /** 0–1 swing amount for odd steps. */
  swing: number;
  /** Track is armed to play with the transport. */
  running: boolean;
  /** 16 gate pads (0/1). */
  gates: number[];
  /** 16 values — Hz for float tracks (host converts midi). */
  values: number[];
  /** 16 probabilities 0–1. */
  probs: number[];
}

export interface TransportSpec {
  bpm: number;
  step: number;
  running: boolean;
  swingEnabled: boolean;
  meterPort: number;
  host?: string;
  tracks: TransportTrack[];
}

/** Max tracks baked into transport (matches UI / OSC arrays). */
export const TRANSPORT_MAX_TRACKS = 16;

/**
 * Build a temporary transport.ck that owns the 16th-note clock and fires
 * pattern targets / gates into shared globals.
 * Control (BPM / run / swing) and pattern patches arrive via bridge OSC.
 */
export function writeTransportFile(
  spec: TransportSpec
): { path: string; source: string } {
  const source = generateTransportSource(spec);
  const outPath = path.join(os.tmpdir(), 'chuck-live-transport.ck');
  fs.writeFileSync(outPath, source, 'utf8');
  return { path: outPath, source };
}

/** Topology fingerprint: names + kinds + gate Events (not pattern data). */
export function transportTopologyKey(tracks: TransportTrack[]): string {
  return tracks
    .slice(0, TRANSPORT_MAX_TRACKS)
    .map((t) => `${t.name}:${t.kind}:${t.gate ?? ''}`)
    .join('|');
}

export function generateTransportSource(spec: TransportSpec): string {
  const host = spec.host ?? '127.0.0.1';
  const bpm = clamp(spec.bpm, 40, 200);
  const step = ((spec.step % 16) + 16) % 16;
  const running = spec.running ? 1 : 0;
  const swingEn = spec.swingEnabled ? 1 : 0;
  const tracks = spec.tracks.slice(0, TRANSPORT_MAX_TRACKS);
  const n = tracks.length;

  const lines: string[] = [
    '// Auto-generated by ChucK Live — do not edit by hand',
    `// Transport clock → OSC playhead @ ${host}:${spec.meterPort}`,
    '// Pattern data: live_seq_* globals (OSC patch); topology baked below',
    '',
    `global float ${LIVE_TRANSPORT.bpm};`,
    `global int ${LIVE_TRANSPORT.step};`,
    `global float ${LIVE_TRANSPORT.stepDur};`,
    `global Event ${LIVE_TRANSPORT.tick};`,
    `global int ${LIVE_TRANSPORT.running};`,
    `global int ${LIVE_TRANSPORT.cmd};`,
    `global int ${LIVE_TRANSPORT.swing};`,
    '',
    `global int ${LIVE_SEQ.g}[256];`,
    `global float ${LIVE_SEQ.v}[256];`,
    `global float ${LIVE_SEQ.p}[256];`,
    `global int ${LIVE_SEQ.gPend}[256];`,
    `global float ${LIVE_SEQ.vPend}[256];`,
    `global float ${LIVE_SEQ.pPend}[256];`,
    `global int ${LIVE_SEQ.muted}[16];`,
    `global int ${LIVE_SEQ.solo}[16];`,
    `global int ${LIVE_SEQ.run}[16];`,
    `global float ${LIVE_SEQ.swingAmt}[16];`,
    `global int ${LIVE_SEQ.mutedPend}[16];`,
    `global int ${LIVE_SEQ.soloPend}[16];`,
    `global int ${LIVE_SEQ.runPend}[16];`,
    `global float ${LIVE_SEQ.swingPend}[16];`,
    `global int ${LIVE_SEQ.armed};`,
    `global int ${LIVE_SEQ.commit};`,
    '',
  ];

  const declared = new Set<string>([
    ...Object.values(LIVE_TRANSPORT),
    ...Object.values(LIVE_SEQ),
  ]);
  for (const t of tracks) {
    if (!declared.has(t.name)) {
      if (t.kind === 'gate') {
        lines.push(`global Event ${t.name};`);
      } else {
        lines.push(`global float ${t.name};`);
      }
      declared.add(t.name);
    }
    if (t.gate && !declared.has(t.gate)) {
      lines.push(`global Event ${t.gate};`);
      declared.add(t.gate);
    }
  }

  // Swing worker wake Events (persistent shreds — no per-step spork).
  for (let i = 0; i < TRANSPORT_MAX_TRACKS; i++) {
    lines.push(`Event swEv${i};`);
    lines.push(`0 => int swStep${i};`);
    lines.push(`0::ms => dur swDur${i};`);
  }

  lines.push(
    '',
    `${bpm} => ${LIVE_TRANSPORT.bpm};`,
    `${step} => ${LIVE_TRANSPORT.step};`,
    `(60.0 / Math.max(40.0, ${LIVE_TRANSPORT.bpm}) / 4.0) => ${LIVE_TRANSPORT.stepDur};`,
    `${running} => ${LIVE_TRANSPORT.running};`,
    `${swingEn} => ${LIVE_TRANSPORT.swing};`,
    `0 => ${LIVE_SEQ.armed};`,
    `0 => ${LIVE_SEQ.commit};`,
    `${n} => int nTracks;`,
    ''
  );

  // Seed live + pending pattern arrays from host snapshot.
  for (let i = 0; i < TRANSPORT_MAX_TRACKS; i++) {
    const t = i < n ? tracks[i] : undefined;
    const gates = pad16(t?.gates, 0).map((g) => (g > 0.5 ? 1 : 0));
    const vals = pad16(t?.values, 0);
    const probs = pad16(t?.probs, 1).map((p) => clamp(p, 0, 1));
    if (t) {
      lines.push(
        `// track ${i}: ${t.name} (${t.kind})${t.gate ? ` gate=${t.gate}` : ''}`
      );
    }
    for (let s = 0; s < 16; s++) {
      const idx = i * 16 + s;
      lines.push(
        `${gates[s]} => ${LIVE_SEQ.g}[${idx}]; ${gates[s]} => ${LIVE_SEQ.gPend}[${idx}];`
      );
      lines.push(
        `${fmtF(vals[s])} => ${LIVE_SEQ.v}[${idx}]; ${fmtF(vals[s])} => ${LIVE_SEQ.vPend}[${idx}];`
      );
      lines.push(
        `${fmtF(probs[s])} => ${LIVE_SEQ.p}[${idx}]; ${fmtF(probs[s])} => ${LIVE_SEQ.pPend}[${idx}];`
      );
    }
    const muted = t?.muted ? 1 : 0;
    const solo = t?.solo ? 1 : 0;
    const run = t?.running ? 1 : 0;
    const swing = fmtF(clamp(t?.swing ?? 0, 0, 1));
    lines.push(`${muted} => ${LIVE_SEQ.muted}[${i}]; ${muted} => ${LIVE_SEQ.mutedPend}[${i}];`);
    lines.push(`${solo} => ${LIVE_SEQ.solo}[${i}]; ${solo} => ${LIVE_SEQ.soloPend}[${i}];`);
    lines.push(`${run} => ${LIVE_SEQ.run}[${i}]; ${run} => ${LIVE_SEQ.runPend}[${i}];`);
    lines.push(
      `${swing} => ${LIVE_SEQ.swingAmt}[${i}]; ${swing} => ${LIVE_SEQ.swingPend}[${i}];`
    );
    lines.push('');
  }

  lines.push(
    'fun void updateDur() {',
    `  (60.0 / Math.max(40.0, ${LIVE_TRANSPORT.bpm}) / 4.0) => ${LIVE_TRANSPORT.stepDur};`,
    '}',
    '',
    'fun void copyPendToLive() {',
    '  for (0 => int i; i < 256; i++) {',
    `    ${LIVE_SEQ.gPend}[i] => ${LIVE_SEQ.g}[i];`,
    `    ${LIVE_SEQ.vPend}[i] => ${LIVE_SEQ.v}[i];`,
    `    ${LIVE_SEQ.pPend}[i] => ${LIVE_SEQ.p}[i];`,
    '  }',
    '  for (0 => int i; i < 16; i++) {',
    `    ${LIVE_SEQ.mutedPend}[i] => ${LIVE_SEQ.muted}[i];`,
    `    ${LIVE_SEQ.soloPend}[i] => ${LIVE_SEQ.solo}[i];`,
    `    ${LIVE_SEQ.runPend}[i] => ${LIVE_SEQ.run}[i];`,
    `    ${LIVE_SEQ.swingPend}[i] => ${LIVE_SEQ.swingAmt}[i];`,
    '  }',
    '}',
    '',
    'fun void applySeqFlags() {',
    `  if (${LIVE_SEQ.commit} != 0) {`,
    '    copyPendToLive();',
    `    0 => ${LIVE_SEQ.commit};`,
    `    0 => ${LIVE_SEQ.armed};`,
    '  }',
    '}',
    '',
    'fun int anySolo() {',
    '  for (0 => int i; i < nTracks; i++) {',
    `    if (${LIVE_SEQ.solo}[i]) return 1;`,
    '  }',
    '  return 0;',
    '}',
    '',
    'fun int trackAudible(int i) {',
    '  if (i < 0 || i >= nTracks) return 0;',
    `  if (!${LIVE_SEQ.run}[i]) return 0;`,
    `  if (${LIVE_SEQ.muted}[i]) return 0;`,
    `  if (anySolo() && !${LIVE_SEQ.solo}[i]) return 0;`,
    '  return 1;',
    '}',
    '',
    'fun void fireTrack(int i, int s) {',
    '  if (!trackAudible(i)) return;',
    '  i * 16 + s => int idx;',
    `  if (${LIVE_SEQ.g}[idx] < 1) return;`,
    `  if (${LIVE_SEQ.p}[idx] < 0.999 && Math.random2f(0.0, 1.0) >= ${LIVE_SEQ.p}[idx]) return;`
  );

  for (let i = 0; i < n; i++) {
    const t = tracks[i];
    lines.push(`  if (i == ${i}) {`);
    if (t.kind === 'gate') {
      lines.push(`    ${t.name}.broadcast();`);
    } else {
      lines.push(`    ${LIVE_SEQ.v}[idx] => ${t.name};`);
      if (t.gate) {
        lines.push(`    ${t.gate}.broadcast();`);
      }
    }
    lines.push('    return;', '  }');
  }
  lines.push('}', '');

  // Persistent swing workers (one per slot).
  for (let i = 0; i < TRANSPORT_MAX_TRACKS; i++) {
    lines.push(
      `fun void swingWorker${i}() {`,
      '  while (true) {',
      `    swEv${i} => now;`,
      `    swDur${i} => now;`,
      `    if (!${LIVE_TRANSPORT.running}) continue;`,
      `    fireTrack(${i}, swStep${i});`,
      '  }',
      '}',
      ''
    );
  }

  lines.push(
    'fun void fireStep(int s) {',
    `  s => ${LIVE_TRANSPORT.step};`,
    `  ${LIVE_TRANSPORT.tick}.broadcast();`,
    '  for (0 => int i; i < nTracks; i++) {',
    `    if (${LIVE_TRANSPORT.swing} && (s % 2) == 1 && ${LIVE_SEQ.swingAmt}[i] > 0.0) {`,
    `      ${LIVE_TRANSPORT.stepDur}::second * Math.min(${LIVE_SEQ.swingAmt}[i], 0.85) => dur d;`
  );

  for (let i = 0; i < TRANSPORT_MAX_TRACKS; i++) {
    lines.push(
      `      if (i == ${i}) {`,
      `        s => swStep${i};`,
      `        d => swDur${i};`,
      `        swEv${i}.broadcast();`,
      '      }'
    );
  }

  lines.push(
    '    } else {',
    '      fireTrack(i, s);',
    '    }',
    '  }',
    '}',
    '',
    'OscOut xmit;',
    `xmit.dest("${host}", ${spec.meterPort});`,
    '',
    'fun void sendPlayhead() {',
    '  xmit.start("/chuck/live_playhead");',
    `  xmit.add(${LIVE_TRANSPORT.step} $ float);`,
    `  xmit.add(${LIVE_TRANSPORT.running} $ float);`,
    '  xmit.send();',
    '}',
    '',
    'fun void applyCmd() {',
    `  if (${LIVE_TRANSPORT.cmd} == 1) {`,
    `    1 => ${LIVE_TRANSPORT.running};`,
    `    0 => ${LIVE_TRANSPORT.cmd};`,
    '  }',
    '}',
    '',
    'fun void clockLoop() {',
    '  while (true) {',
    '    applyCmd();',
    '    applySeqFlags();',
    '    updateDur();',
    `    if (${LIVE_TRANSPORT.running}) {`,
    `      fireStep(${LIVE_TRANSPORT.step});`,
    '      sendPlayhead();',
    `      ${LIVE_TRANSPORT.stepDur}::second => now;`,
    `      (${LIVE_TRANSPORT.step} + 1) % 16 => int next;`,
    `      if (next == 0 && ${LIVE_SEQ.armed} != 0) {`,
    '        copyPendToLive();',
    `        0 => ${LIVE_SEQ.armed};`,
    '      }',
    `      next => ${LIVE_TRANSPORT.step};`,
    '    } else {',
    '      20::ms => now;',
    '    }',
    '  }',
    '}',
    ''
  );

  for (let i = 0; i < TRANSPORT_MAX_TRACKS; i++) {
    lines.push(`spork ~ swingWorker${i}();`);
  }
  lines.push('spork ~ clockLoop();', 'while (true) 1::second => now;', '');

  return lines.join('\n');
}

function pad16(arr: number[] | undefined, fill: number): number[] {
  const out = (arr ?? []).slice(0, 16);
  while (out.length < 16) {
    out.push(fill);
  }
  return out;
}

function clamp(n: number, min: number, max: number): number {
  if (!Number.isFinite(n)) {
    return min;
  }
  return Math.max(min, Math.min(max, n));
}

function fmtF(n: number): string {
  if (!Number.isFinite(n)) {
    return '0.0';
  }
  const s = n.toFixed(6);
  return s.includes('.') ? s : s + '.0';
}
