import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { LIVE_TRANSPORT } from './bridgeGen';

/** One sequencer track baked into the transport shred. */
export interface TransportTrack {
  name: string;
  kind: 'float' | 'gate';
  /** Optional Event name for float lanes (gate bang). */
  gate?: string;
  muted: boolean;
  solo: boolean;
  /** 0–1 swing amount for odd steps. */
  swing: number;
  /** Track is armed to play with the transport. */
  running: boolean;
  /** 16 gate pads (0/1). */
  gates: number[];
  /** 16 values — Hz for float tracks (host converts midi). */
  values: number[];
  /** 16 probabilities 0–1. */
  probs: number[];
}

export interface TransportSpec {
  bpm: number;
  step: number;
  running: boolean;
  swingEnabled: boolean;
  meterPort: number;
  host?: string;
  tracks: TransportTrack[];
}

/**
 * Build a temporary transport.ck that owns the 16th-note clock and fires
 * pattern targets / gates into shared globals.
 * Control (BPM / run / swing) arrives via bridge OSC → live_* globals.
 */
export function writeTransportFile(
  spec: TransportSpec
): { path: string; source: string } {
  const source = generateTransportSource(spec);
  const outPath = path.join(os.tmpdir(), 'chuck-live-transport.ck');
  fs.writeFileSync(outPath, source, 'utf8');
  return { path: outPath, source };
}

export function generateTransportSource(spec: TransportSpec): string {
  const host = spec.host ?? '127.0.0.1';
  const bpm = clamp(spec.bpm, 40, 200);
  const step = ((spec.step % 16) + 16) % 16;
  const running = spec.running ? 1 : 0;
  const swingEn = spec.swingEnabled ? 1 : 0;
  const tracks = spec.tracks.slice(0, 16);

  const lines: string[] = [
    '// Auto-generated by ChucK Live — do not edit by hand',
    `// Transport clock → OSC playhead @ ${host}:${spec.meterPort}`,
    '// BPM/run/swing via bridge OSC → live_* globals',
    '',
    `global float ${LIVE_TRANSPORT.bpm};`,
    `global int ${LIVE_TRANSPORT.step};`,
    `global float ${LIVE_TRANSPORT.stepDur};`,
    `global Event ${LIVE_TRANSPORT.tick};`,
    `global int ${LIVE_TRANSPORT.running};`,
    `global int ${LIVE_TRANSPORT.cmd};`,
    `global int ${LIVE_TRANSPORT.swing};`,
    '',
  ];

  const declared = new Set<string>(Object.values(LIVE_TRANSPORT));
  for (const t of tracks) {
    if (!declared.has(t.name)) {
      if (t.kind === 'gate') {
        lines.push(`global Event ${t.name};`);
      } else {
        lines.push(`global float ${t.name};`);
      }
      declared.add(t.name);
    }
    if (t.gate && !declared.has(t.gate)) {
      lines.push(`global Event ${t.gate};`);
      declared.add(t.gate);
    }
  }

  lines.push(
    '',
    `${bpm} => ${LIVE_TRANSPORT.bpm};`,
    `${step} => ${LIVE_TRANSPORT.step};`,
    `(60.0 / Math.max(40.0, ${LIVE_TRANSPORT.bpm}) / 4.0) => ${LIVE_TRANSPORT.stepDur};`,
    `${running} => ${LIVE_TRANSPORT.running};`,
    `${swingEn} => ${LIVE_TRANSPORT.swing};`,
    `${tracks.length} => int nTracks;`,
    ''
  );

  for (let i = 0; i < tracks.length; i++) {
    const t = tracks[i];
    const gates = pad16(t.gates, 0).map((g) => (g > 0.5 ? 1 : 0));
    const vals = pad16(t.values, 0);
    const probs = pad16(t.probs, 1).map((p) => clamp(p, 0, 1));
    lines.push(`// track ${i}: ${t.name} (${t.kind})`);
    lines.push(`[${gates.join(',')}] @=> int t${i}_g[];`);
    lines.push(`[${vals.map(fmtF).join(',')}] @=> float t${i}_v[];`);
    lines.push(`[${probs.map(fmtF).join(',')}] @=> float t${i}_p[];`);
    lines.push(`${fmtF(clamp(t.swing, 0, 1))} => float t${i}_swing;`);
    lines.push(`${t.muted ? 1 : 0} => int t${i}_muted;`);
    lines.push(`${t.solo ? 1 : 0} => int t${i}_solo;`);
    lines.push(`${t.running ? 1 : 0} => int t${i}_run;`);
    lines.push('');
  }

  lines.push(
    'fun void updateDur() {',
    `  (60.0 / Math.max(40.0, ${LIVE_TRANSPORT.bpm}) / 4.0) => ${LIVE_TRANSPORT.stepDur};`,
    '}',
    '',
    'fun int anySolo() {'
  );
  for (let i = 0; i < tracks.length; i++) {
    lines.push(`  if (t${i}_solo) return 1;`);
  }
  lines.push('  return 0;', '}', '');

  lines.push('fun int trackAudible(int i) {');
  for (let i = 0; i < tracks.length; i++) {
    lines.push(
      `  if (i == ${i}) {`,
      `    if (!t${i}_run) return 0;`,
      `    if (t${i}_muted) return 0;`,
      `    if (anySolo() && !t${i}_solo) return 0;`,
      '    return 1;',
      '  }'
    );
  }
  lines.push('  return 0;', '}', '');

  lines.push('fun void fireTrack(int i, int s) {', '  if (!trackAudible(i)) return;');
  for (let i = 0; i < tracks.length; i++) {
    const t = tracks[i];
    lines.push(`  if (i == ${i}) {`);
    lines.push(`    if (t${i}_g[s] < 1) return;`);
    lines.push(
      `    if (t${i}_p[s] < 0.999 && Math.random2f(0.0, 1.0) >= t${i}_p[s]) return;`
    );
    if (t.kind === 'gate') {
      lines.push(`    ${t.name}.broadcast();`);
    } else {
      lines.push(`    t${i}_v[s] => ${t.name};`);
      if (t.gate) {
        lines.push(`    ${t.gate}.broadcast();`);
      }
    }
    lines.push('    return;', '  }');
  }
  lines.push('}', '');

  lines.push(
    'fun void fireTrackSwing(int i, int s, dur delay) {',
    '  delay => now;',
    `  if (!${LIVE_TRANSPORT.running}) return;`,
    '  fireTrack(i, s);',
    '}',
    '',
    'fun void fireStep(int s) {',
    `  s => ${LIVE_TRANSPORT.step};`,
    `  ${LIVE_TRANSPORT.tick}.broadcast();`,
    '  for (0 => int i; i < nTracks; i++) {'
  );

  for (let i = 0; i < tracks.length; i++) {
    lines.push(
      `    if (i == ${i}) {`,
      `      if (${LIVE_TRANSPORT.swing} && (s % 2) == 1 && t${i}_swing > 0.0) {`,
      `        ${LIVE_TRANSPORT.stepDur}::second * Math.min(t${i}_swing, 0.85) => dur d;`,
      `        spork ~ fireTrackSwing(${i}, s, d);`,
      '      } else {',
      `        fireTrack(${i}, s);`,
      '      }',
      '    }'
    );
  }

  lines.push(
    '  }',
    '}',
    '',
    'OscOut xmit;',
    `xmit.dest("${host}", ${spec.meterPort});`,
    '',
    'fun void sendPlayhead() {',
    '  xmit.start("/chuck/live_playhead");',
    `  xmit.add(${LIVE_TRANSPORT.step} $ float);`,
    `  xmit.add(${LIVE_TRANSPORT.running} $ float);`,
    '  xmit.send();',
    '}',
    '',
    'fun void applyCmd() {',
    `  if (${LIVE_TRANSPORT.cmd} == 1) {`,
    `    1 => ${LIVE_TRANSPORT.running};`,
    `    0 => ${LIVE_TRANSPORT.cmd};`,
    '  }',
    `  if (${LIVE_TRANSPORT.cmd} == 0) {`,
    '    // cmd stays 0; host also writes live_running directly',
    '  }',
    '}',
    '',
    'fun void clockLoop() {',
    '  while (true) {',
    '    applyCmd();',
    '    updateDur();',
    `    if (${LIVE_TRANSPORT.running}) {`,
    `      fireStep(${LIVE_TRANSPORT.step});`,
    '      sendPlayhead();',
    `      ${LIVE_TRANSPORT.stepDur}::second => now;`,
    `      (${LIVE_TRANSPORT.step} + 1) % 16 => ${LIVE_TRANSPORT.step};`,
    '    } else {',
    '      20::ms => now;',
    '    }',
    '  }',
    '}',
    '',
    'spork ~ clockLoop();',
    'while (true) 1::second => now;',
    ''
  );

  return lines.join('\n');
}

function pad16(arr: number[] | undefined, fill: number): number[] {
  const out = (arr ?? []).slice(0, 16);
  while (out.length < 16) {
    out.push(fill);
  }
  return out;
}

function clamp(n: number, min: number, max: number): number {
  if (!Number.isFinite(n)) {
    return min;
  }
  return Math.max(min, Math.min(max, n));
}

function fmtF(n: number): string {
  if (!Number.isFinite(n)) {
    return '0.0';
  }
  const s = n.toFixed(6);
  return s.includes('.') ? s : s + '.0';
}
